name:                arvo
version:             0.1.0.0
github:              "githubuser/arvo"
license:             BSD-3-Clause
author:              "Tomislav Bodor"
maintainer:          "tomislav@bodor.net.nz"
copyright:           "2024 Tomislav Bodor"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tbodor/arvo#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- repline
- haskeline
- pretty-simple

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  arvo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arvo

tests:
  arvo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arvo
    - hspec
    - hspec-discover
    - hspec-megaparsec
    - QuickCheck
